### ISSUE TITLE
Concept Structure

### ISSUE THREAD

**Issue by JarbasAI** [ElliotTheRobot/LILACS-mycroft-core#2]
Mycroft will need a data-structure that could be any concept, this data structure would contain:

- parent_concepts -> concept is an example of parent_concept
- child_concepts -> all childs concepts are examples of concept
- data -> arbitrary data about the concept, for starters a summary from wikipedia would be enough

Example human concept:

parents = [mammal, animal, omnivore, alive, female, male]
childs = [ john, joe, jane, mary]
data = {"summary": "Modern humans are the only extant members of Hominina tribe, a branch of the tribe Hominini belonging to the family of great apes. They are characterized by erect posture and bipedal locomotion; manual dexterity and increased tool use, compared to other animals; and a general trend toward larger, more complex brains and societies"}

Connecting these will be other issue

commit: https://github.com/HeinzSchmidt/LILACS-mycroft-core/commit/59211245567c3601a5d11fbd697754e090fa21f4

**Comment by HeinzSchmidt** [comment]
This would enable MyCroft to answer a question like:

Is a chicken (child_concept) a carnivore (parent_concept)

Chicken would not have a parent concept of carnivore - result equals fasle
MyCroft says: "No it's not"
