### ISSUE TITLE
Deduction Back Ends

### ISSUE THREAD

**Issue by JarbasAI** [ElliotTheRobot/LILACS-mycroft-core#4]
The purpose of this would be to deduce/learn anything from existing concepts database

This should be abstracted and configurable in config, similiar to [AudioBackEnd](https://github.com/forslund/mycroft-core/tree/audio-service/)

Idea is, when asking a question mycroft doesnt know, it will try default backend, in case of fail try other backends until sucess

Default: Ask user
Wikipedia: Seach wikipedia
WolphramAlpha: Ask wolpham alpha
Other: Possible databases -> https://github.com/caesar0301/awesome-public-datasets

A mechanism to add/choose backends is needed, a separate issue should be made for each backend

Usage example:

 -   is a cow an animal?
  -  parse for concepts (cow, parents = animal)
  -  check if cow concept exists
        - yes
            - check if animal is in cow parent_concepts
        - no
            - check backend for cow
            - "wikipedia says yes, is this correct?"
                   - yes - create cow concept
             - not found
                   - fall back to ask user backend "is cow an animal"
                         - yes   -> create cow concept with animal parent_concept
                         - no -> ask what is a cow and create cow concept with "answer" as parent

**Comment by penrods** [comment]
If you aren't aware of it, you might want to look at Wikidata (https://www.wikidata.org/wiki/Wikidata:Introduction) instead of Wikipedia.  It provides structured data instead of the freeform stuff in Wikipedia.  Not all of Wikipedia is in Wikidata, but there is quite a bit and the organizational approach is interesting.

Here is the Wikidata entry for Barack Obama -- https://www.wikidata.org/wiki/Q76

**Comment by JarbasAI** [comment]
wikidata seems the best option, a combination with wikipedia would be useful (a summary entry to read out loud) 

this seems the most promising way to go https://github.com/Dorialexander/Wikidaesthetics 

wikidata falls really well into the structure of parents and childs

**Comment by JarbasAI** [comment]
https://github.com/ElliotTheRobot/LILACS-mycroft-core/tree/dev/mycroft/knowledge

a service to manage individual backends was added, this will listen for messages on the messagebus and manage services to adquire knowledge

closing this issue now, open new issues for each backend
